Fixing issue with bisect module not being loaded
When running this formula in production there is a stacktrace being
generated due to the bisect module not being found in the function
context.

```
NameError: global name 'bisect' is not defined
```

Changed the import strategy to simplify namespace.